import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { NextAuthProvider } from "../providers/NextAuthProvider";
import { ToasterProvider } from "../providers/ToasterProvider";

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="bg-gradient-to-br from-slate-900 to-indigo-950 text-slate-100 min-h-screen flex flex-col overflow-x-hidden antialiased">
        <NextAuthProvider>
          <ToasterProvider />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
